// AUTO-GENERATED from /tmp/airvues_schema.json on 2026-04-26.
// Field names are the EXACT Airtable display names (including emoji and special chars).
// Reference fields via bracket notation: Tables.Stories.fields["Story Status"].id
// Source of truth: live Airtable Meta API at https://api.airtable.com/v0/meta/bases/app4vhhWMbRFOloOU/tables
//
// To regenerate: re-run the schema generator (see scripts/regenerate-schema.py).
// CI guard: scripts/verify-schema.ts validates this file against live Meta API on prebuild.

export const BASE_ID = 'app4vhhWMbRFOloOU';

export const Tables = {
  FormSubmissions: {
    id: "tbldeKGlLgRWSIzTh",
    name: "\u26aa\ufe0f Form Submissions",
    fields: {
      "Intake ID": { id: "fld3tEvaZA1yNcBX6", type: "formula" },
      "Manual Ingest ": { id: "fldEudWdETXrjIV7m", type: "checkbox" },
      "Created": { id: "fldiSkrSb0IjqN5eK", type: "createdTime" },
      "\u2728Suggested Project Name": { id: "fldLBxRVnBapHykGJ", type: "aiText" },
      "Exiting Client Checkbox": { id: "fld7jSrc1BD6A8eaA", type: "checkbox" },
      "Intake #": { id: "fldUyvPxmgVLNnahQ", type: "formula" },
      "Client Feedback Form": { id: "fldEDbVwbQc9637tx", type: "formula" },
      "Feasibility Status": { id: "fldIwOPnPxwBFmmQs", type: "singleSelect", options: { choices: [{"name": "Pending Dev Estimate"}, {"name": "Estimates Ready"}, {"name": "More Information Needed"}, {"name": "Awaiting Response"}, {"name": "Quote/Invoice Sent, Awaiting Initial Payment"}, {"name": "Yes \u2013 Ready to Proceed"}, {"name": "Ready to Close Project"}, {"name": "Unresponsive - Possible Lost Lead"}, {"name": "Graveyard \ud83d\udc7b"}, {"name": "Pending Dev Assignment"}, {"name": "Consultation Offered"}, {"name": "Project Completed"}] } },
      "Preferred Payment Platform": { id: "fldyr7huQYJoMiVCa", type: "singleSelect", options: { choices: [{"name": "Airvues Invoice"}, {"name": "Fiverr Gig"}] } },
      "Existing Client?": { id: "fldtQGv1eY2f0HKlc", type: "multipleRecordLinks" },
      "Existing Company?": { id: "fldhZ7YsAVQ2kbexc", type: "multipleRecordLinks" },
      "How can we help you?": { id: "fldxqzBNEHbawpXT5", type: "multipleSelects", options: { choices: [{"name": "Analytics and Reporting"}, {"name": "Bug Fix"}, {"name": "Content Update"}, {"name": "Custom Development"}, {"name": "Data Migration"}, {"name": "Design Update"}, {"name": "Integration"}, {"name": "Maintenance and Support"}, {"name": "New Feature Development"}, {"name": "Performance Optimization"}, {"name": "Requirements Gathering"}, {"name": "Schedule a Consultation [WIP]"}, {"name": "Security Enhancement"}, {"name": "System Upgrade"}, {"name": "Technical Documentation"}, {"name": "Training and Onboarding"}, {"name": "Other"}] } },
      "First Name": { id: "fldnV9beHIefAkRtX", type: "singleLineText" },
      "Last Name": { id: "fldyMhv2ywJooNm2e", type: "singleLineText" },
      "Company Name": { id: "fldpXWmU6r6QqNZXX", type: "singleLineText" },
      "Fiverr Account": { id: "fld6FaMtaPClBiGkM", type: "singleLineText" },
      "Email": { id: "fldGSVqIDHEUUfRkW", type: "email" },
      "Phone": { id: "fldnJPnb4Oi7gTZof", type: "phoneNumber" },
      "Website (from \ud83c\udfed Companies)": { id: "fldZQlW53epKpfBN6", type: "multipleLookupValues" },
      "Drive Folder (from \ud83c\udfed Companies)": { id: "fldhQbdQMmH4zYgBq", type: "multipleLookupValues" },
      "Miro Folder (from \ud83c\udfed Companies)": { id: "fldPr3Aw5V991NB6Y", type: "multipleLookupValues" },
      "Website 1": { id: "fldUSMbTbu3sjl8IU", type: "url" },
      "Website 2": { id: "fld9F7a6XhqPidrwx", type: "url" },
      "Company Description": { id: "fldNGedGVMlzTSQG0", type: "multilineText" },
      "Software": { id: "fldyVSgIoV6T4t6Se", type: "multipleRecordLinks" },
      "Other Tools (Not Listed)": { id: "fld8wFljRcAtYwgUr", type: "multilineText" },
      "Project Goals and Success Criteria": { id: "fldjZybvDn9FiQB2a", type: "richText" },
      "Detailed Request Description": { id: "fldxN9zP2Bpg9Gjxf", type: "richText" },
      "Desired Delivery Date": { id: "fld0FcblcRnJ5MpVs", type: "date" },
      "Priority": { id: "fldBVPBjLW92L7mEM", type: "singleSelect", options: { choices: [{"name": "Urgent"}, {"name": "High"}, {"name": "Medium"}, {"name": "Low"}] } },
      "What is your Budget": { id: "fldUpwQGvS8Ufp0eq", type: "currency" },
      "Update Personal Information?": { id: "fldL4qjtBuPx0XgoS", type: "singleSelect", options: { choices: [{"name": "Yes"}, {"name": "No"}] } },
      "Project Attachments": { id: "fldRLvAp1eMnrn8J9", type: "multipleAttachments" },
      "Quotes [Deprecated]": { id: "fldC7YimKqgra5Es4", type: "singleLineText" },
      "Supporting Documentation": { id: "fld9PCGEK3KXd0MpA", type: "richText" },
      "Do you have a process or workflow already established?": { id: "fldUzZmCWLbr3aM7W", type: "singleSelect", options: { choices: [{"name": "Yes"}, {"name": "No"}] } },
      "Country": { id: "fldGibgCCayZb26kq", type: "multipleRecordLinks" },
      "Page Navigation": { id: "fldAnCTVQ6Y7hiqYk", type: "singleSelect", options: { choices: [{"name": "Show AI"}, {"name": "Hide AI"}] } },
      "Hourly Rate (from \ud83c\udfed Companies)": { id: "fldr2zcltdE2an0SQ", type: "multipleLookupValues" },
      "Contract Type (from \ud83c\udfed Companies)": { id: "fldZZCpMhuMrvWCIS", type: "multipleLookupValues" },
      "Legal Agreement (from \ud83c\udfed Companies)": { id: "fldekxANkdBSSzhcY", type: "multipleLookupValues" },
      "Preferred Business (from \ud83c\udfed Companies)": { id: "fldoWVE0ID9bNQGWF", type: "multipleLookupValues" },
      "\u2728Project Name": { id: "fldhtcUwAo8Gl2nJI", type: "formula" },
      "Full Name (from \ud83d\udc64 Clients)": { id: "fldaviTHFmm2atEE8", type: "multipleLookupValues" },
      "Name (from \ud83c\udfed Companies)": { id: "fldVkhR9kCxDCTGCd", type: "multipleLookupValues" },
      "Airtable Base": { id: "fldcrpdCAchgiQ63M", type: "url" },
      "Proposed Solution": { id: "fldM6dpwfY8Gm5P3D", type: "richText" },
      "\u2728AI Website Summary": { id: "fldosnvsnm070Wsq6", type: "aiText" },
      "Submissions Source": { id: "fld378hv8bhl9IJ4i", type: "singleSelect", options: { choices: [{"name": "External Intake Form"}, {"name": "Internal Interface Form"}, {"name": "Website Meeting Workflow"}] } },
      "Media Assets": { id: "fldqRigHUwTZtb7PB", type: "singleLineText" },
      "Attachments (from Media Assets)": { id: "flds1vpwtNYLh2rVQ", type: "multipleLookupValues" },
      "Status Grouping": { id: "fldkomjYuXQCPdNnb", type: "formula" },
      "BA Assigned": { id: "fldGc6FB8MzEe3o8t", type: "multipleRecordLinks" },
      "Engineer Assigned": { id: "flda2YEKeFev0WeOR", type: "multipleRecordLinks" },
      "Slack User name (from Engineer Assigned)": { id: "fldqDCei2yjqYVdNN", type: "multipleLookupValues" },
      "Invoices": { id: "fldwmJYf8sUgaktAL", type: "multipleRecordLinks" },
      "Date (from Invoices)": { id: "fldDWBJHfAE4UjUgY", type: "multipleLookupValues" },
      "Invoice Amount Paid": { id: "fldOGKXpAIF5J6j9T", type: "rollup" },
      "Quoted Project Cost": { id: "fld9ZkmF0NataHmfk", type: "rollup" },
      "Quoted Project Hours": { id: "fldiSICujY4Ld2gDk", type: "rollup" },
      "Completion Progress": { id: "fldw4GcGjKZ3pRJg2", type: "formula" },
      "Fiverr Status (from Invoices)": { id: "fldn0N2BkEiC6S7BI", type: "multipleLookupValues" },
      "Invoice Status (from Invoices)": { id: "fld7yrJIt8wfgnJbY", type: "multipleLookupValues" },
      "Invoice Status Last Modified (from Invoices)": { id: "fld8w9Oz2o9TEGlRs", type: "multipleLookupValues" },
      "Days of Engineering": { id: "fldzDVx79DUzQFnsm", type: "formula" },
      "Project Hours Per Workday": { id: "fldq2owoXpyPCmPgw", type: "formula" },
      "Engineer Delivery": { id: "fldIGWB4FgQozafqG", type: "singleSelect", options: { choices: [{"name": "Engineering in Progress"}, {"name": "Engineer Delivered"}, {"name": "Revisions Needed"}] } },
      "Initial Payment Status": { id: "fldsu85V290kC8gDv", type: "formula" },
      "AI Engineer on Request": { id: "fldpQWpaWV2fpoF1P", type: "checkbox" },
      "Client Delivery Due Date": { id: "fldKygGi5cFGIkZI7", type: "multipleLookupValues" },
      "Engineer Delivery Due Date": { id: "fldd04S32gCylidbU", type: "formula" },
      "Days to Delivery": { id: "fldncfswGsW6VyUOW", type: "formula" },
      "Time to Delivery": { id: "flduSS4XA6STRjamG", type: "formula" },
      "Admins": { id: "fld9Ty5WvsBWp2BdI", type: "multipleCollaborators" },
      "Autonumber": { id: "fldlh18Ji1h87rvoV", type: "autoNumber" },
      "Manual Approval": { id: "fldetY7AyCIIEXsKR", type: "checkbox" },
      "Fiverr URL": { id: "fldjpozYapNYAgea0", type: "formula" },
      "Quotes": { id: "fldo4CsOhTPEGs4D6", type: "multipleRecordLinks" },
      "Intake Proposals": { id: "fldZcF14XuGzTWd6g", type: "multipleRecordLinks" },
      "Unique Intake Proposal Form": { id: "flda4SB4oNqRieI1C", type: "formula" },
      "Intake Record ID": { id: "fldhQIZn5AZwyyFvH", type: "formula" },
      "Submit a Proposal": { id: "fldvHnjC7rUwE15Od", type: "button" },
      "Average Proposal $": { id: "fldsaJe43bU9eJGoZ", type: "rollup" },
      "PM Notes": { id: "fldP8e10pgh1KzIg0", type: "richText" },
      "Number of Proposals Raw": { id: "fld9aaiJ3xloVCdWP", type: "count" },
      "# of Proposals": { id: "fldoRrQCz1z6nEXnS", type: "formula" },
      "Submitter (from Intake Proposals)": { id: "fldjnW8H8a094zbG0", type: "multipleLookupValues" },
      "Team Calendar": { id: "fldUAftYScveCo8fk", type: "multipleRecordLinks" },
      "PM Assigned (Deprecated)": { id: "fldscoX41l0TO3C1a", type: "multipleCollaborators" },
      "Interested ?": { id: "fldi9ndJQtOw2LGbs", type: "multipleLookupValues" },
      "Estimated Project Cost (from Intake Proposals)": { id: "fldiW36jL3O8GYWkN", type: "multipleLookupValues" },
      "Logo (from Existing Company?)": { id: "fldC9a60sgx3O9tKL", type: "multipleLookupValues" },
      "Name (from Existing Company?)": { id: "fldQZXKjfrKsL9dMb", type: "multipleLookupValues" },
      "\u26a0\ufe0fRecommended Fields\u26a0\ufe0f": { id: "fld800xAZZRz7UYtM", type: "formula" },
      "Airvues Terms of Service (from Existing Company?)": { id: "fldWEsjeyGJnRpoJa", type: "multipleLookupValues" },
      "Graveyard Reason": { id: "fldcobQGZVLEqcdsU", type: "singleSelect", options: { choices: [{"name": "Client- Expensive"}, {"name": "Client- Went with another vendor"}, {"name": "Client- Never responded"}, {"name": "Airvues: No - No Capacity"}, {"name": "Airvues: No - Not Enough Budget"}, {"name": "Other"}] } },
      "Quick Win": { id: "fldenlO1VoRuW8Pdn", type: "checkbox" },
      "Agenda": { id: "fldfUKH8IDy51P4Il", type: "multipleRecordLinks" },
      "Proposal Submitters": { id: "fldlRRHdIzv3IV8yp", type: "formula" },
      "Epics": { id: "fldUjqBZ1cgdDaskh", type: "singleLineText" },
      "Feasible": { id: "fld4V9elN9xA2UhQY", type: "rollup" },
      "Not Feasible": { id: "fldyiYeQHBNpjaa6K", type: "rollup" },
      "Not Enough Information": { id: "fldIn3MVbphlimmwq", type: "rollup" },
      "Team Resource Allocation & Daily Standups": { id: "fldZPdGcU6a9Z3hsY", type: "multipleRecordLinks" },
      "Proposed Solution (from Intake Proposals)": { id: "fldtQDrvdltRbGV6H", type: "multipleLookupValues" },
      "Ai Engineer Trigger": { id: "fldNM4UQP63vtWkj7", type: "formula" },
      "AI Engineer Completed": { id: "fldsciZqrIDslIylZ", type: "formula" },
      "Client Feedback": { id: "fldgeQGEatAgYcmnK", type: "multipleRecordLinks" },
    },
  },
  Leads: {
    id: "tblpOwt2GB1YE2bm3",
    name: "\u26aa\ufe0f Leads",
    fields: {
      "Name": { id: "fldTCRZzk3mopoUzL", type: "singleLineText" },
      "First Name": { id: "fldOJtsP64mAzw31f", type: "aiText" },
      "Last Name": { id: "fld8p4OiaJSreyQk3", type: "aiText" },
      "Email": { id: "fldPeymCj1u1L2au0", type: "email" },
      "Company Name": { id: "fldvzYfnuhBUqu8FA", type: "singleLineText" },
      "Title": { id: "fldP76S4uUMFCp09e", type: "singleLineText" },
      "Budget": { id: "fldSCamxXoq4riKf4", type: "singleSelect", options: { choices: [{"name": "<$500"}, {"name": "$1000 - $2000"}, {"name": "$5000+"}] } },
      "What are you looking to build?": { id: "fldnh5Iu3SC5lxtfS", type: "multilineText" },
      "Source": { id: "fldHMuamSM7g07b55", type: "singleSelect", options: { choices: [{"name": "Manually Scheduled"}, {"name": "From Fillout"}] } },
      "Meeting Date": { id: "fldVEuknYTnnVGgfn", type: "dateTime" },
      "End Meeting Date": { id: "fldJOvuaABFVvyKSd", type: "formula" },
      "Meeting Link": { id: "fldKNapA6ozlXqWnN", type: "url" },
      "Client Introduction": { id: "fld8bXl3I7X3R95n8", type: "aiText" },
      "Created Time": { id: "fldneTPpA6QtFxBlQ", type: "createdTime" },
      "Time from submission": { id: "fldU0ahkLMSOAq9WZ", type: "formula" },
      "Meeting Date (Formatted)": { id: "fldY0EtTAAjNs0aY8", type: "formula" },
      "\u26aa\ufe0f Quotes": { id: "fld6rvQvcuLzdc4Xe", type: "multipleRecordLinks" },
      "Status": { id: "fldY6XKOYeqtIKuBj", type: "singleSelect", options: { choices: [{"name": "New Lead"}, {"name": "Needs Review"}, {"name": "In Proposal Stage"}, {"name": "Sold"}, {"name": "Not Sold"}] } },
      "Paste Meeting Transcript": { id: "fldgvn4i6Y19CWYnY", type: "multilineText" },
      "Attach Supporting Documentations": { id: "fldQsxMwiEYbnDUxv", type: "multipleAttachments" },
      "Team Member Lead Assesser": { id: "fldyneqzPK3mCmxbk", type: "multipleRecordLinks" },
      "Status (from \u26aa\ufe0f Quotes)": { id: "fld18EXEWFftg36zS", type: "multipleLookupValues" },
      "Days to Meeting": { id: "fldw426GnFWkfmeaY", type: "formula" },
    },
  },
  Quotes: {
    id: "tbldBIfAeRAunipbk",
    name: "\u26aa\ufe0f Quotes",
    fields: {
      "Quote ID": { id: "fldSS4tOEq7sHgpPJ", type: "formula" },
      "Form Submission": { id: "fldIrvD2YkZ5ev1qy", type: "multipleRecordLinks" },
      "Lead": { id: "fldoGXGjGv3jXJXmN", type: "multipleRecordLinks" },
      "Admins (from Form Submission)": { id: "fldZwqjw0YKfGJaKB", type: "multipleLookupValues" },
      "Intake Proposals (from Form Submission)": { id: "fldqwKymAyaRiRWDx", type: "multipleLookupValues" },
      "\u26a0\ufe0f Recommended Fields\u26a0\ufe0f": { id: "fldmuzDp6lUuvqKhw", type: "multipleLookupValues" },
      "Prepared Date": { id: "fld1Xegrp9yRCXmfG", type: "date" },
      "Project Name": { id: "fldbJs5J4c1eQLC69", type: "singleLineText" },
      "Company Name": { id: "fld3HBa2PRe362JHs", type: "multipleLookupValues" },
      "Existing Company? (from Form Submission)": { id: "fld3ZZxUC6AHJTkPM", type: "multipleLookupValues" },
      "Prepared for": { id: "fldBR8ksKYyHDWQUV", type: "multipleRecordLinks" },
      "Primary Email (from Prepared for)": { id: "fldApRVEbMuBvflJF", type: "multipleLookupValues" },
      "Client Name": { id: "fldPAN9YPB8DILXYF", type: "multipleLookupValues" },
      "Logo (from Existing Company?) (from Form Submission)": { id: "fldnJZOqRsdMyqrcb", type: "multipleLookupValues" },
      "Quote Attachment": { id: "fld7gwrCW2iD36GLU", type: "multipleAttachments" },
      "Existing Client? (from Form Submission)": { id: "fld6uZfuQigJamscg", type: "multipleLookupValues" },
      "Attachments (from Media Assets) (from Form Submission)": { id: "fldq6pQ5UekPUqemv", type: "multipleLookupValues" },
      "Intake # (from Form Submission)": { id: "fldvMvKQccv5Wohbp", type: "multipleLookupValues" },
      "\u2728Suggested Project Name (from Form Submission)": { id: "fldLSYiqAaabdaY8A", type: "multipleLookupValues" },
      "Status": { id: "fldInv0B8qcnxQoef", type: "singleSelect", options: { choices: [{"name": "Draft"}, {"name": "Sent. Awaiting Approval."}, {"name": "Approved and Signed"}, {"name": "Awaiting Payment"}, {"name": "Project In Progress"}, {"name": "Paid"}, {"name": "Cancelled"}, {"name": "Rejected"}, {"name": "Auditing \ud83d\udea9"}] } },
      "Autonumber": { id: "fldCKeNmy17G1FMxU", type: "autoNumber" },
      "Quote Unique ID": { id: "fldqtLXKxT0violAV", type: "formula" },
      "Problem Statement & Our Solution": { id: "fldFuPYgd0dlXmwoh", type: "richText" },
      "Quote Objectives": { id: "fld2rZmDRIJJ9j7aK", type: "richText" },
      "Quote Timeline and Deliverables": { id: "fldFKPQbLKHlFaK84", type: "richText" },
      "Prepared by": { id: "fldKiBKputARtZGKD", type: "multipleRecordLinks" },
      "Airtable Account (from Created By)": { id: "fldpLanQMzOQgfcua", type: "multipleLookupValues" },
      "Legal Clause": { id: "fldC12YSSb3UqdSpT", type: "richText" },
      "Signed Offer": { id: "fld0coRzLLn2i5Meg", type: "multipleAttachments" },
      "Proposal Details to be used for AI Quote": { id: "flda1sPZrzRsCpEh8", type: "richText" },
      "Description": { id: "flddHzs1SOr71npIP", type: "multilineText" },
      "Created": { id: "fldlSCeaPnNQ2wydf", type: "createdTime" },
      "Created By": { id: "fldB1Dsa9laXdn16X", type: "createdBy" },
      "Legal Agreement - Part 1": { id: "fldtIYhFoyc3cCu8E", type: "formula" },
      "Legal Agreement - Part 2": { id: "fldFIp3Q6cbaTMNni", type: "formula" },
      "Click to Print \ud83d\udc49\ud83c\udffb": { id: "fldvBUKNOnYc8EI7N", type: "button" },
      "Print in Page Designer": { id: "fldx9v8vp15BDLNHd", type: "formula" },
      "\ud83d\udd3aRequired Fields\ud83d\udd3a": { id: "fldgbKBzPmWC7L2WJ", type: "formula" },
      "Invoices": { id: "fld4ON95AfXXICVcD", type: "multipleRecordLinks" },
      "Initial Invoice Link": { id: "fld3D1reRdDhr8SXu", type: "multipleLookupValues" },
      "Initial Invoice Link Paid": { id: "fldJdkzp1PEamm20f", type: "multipleLookupValues" },
      "Total Project Cost": { id: "fldoPgUvJVkMfqKc6", type: "currency" },
      "Total Paid": { id: "fldzBupcBclZ1xppI", type: "rollup" },
      "Amount Owed": { id: "fldkJ428Uby7fVXZh", type: "formula" },
      "Stories": { id: "fldRExTxGKWgRZwfq", type: "multipleRecordLinks" },
      "Detailed Request Description (from Form Submission)": { id: "fldIgjSNWMkcz0yYo", type: "multipleLookupValues" },
      "Project Goals and Success Criteria (from Form Submission)": { id: "fld2NIksVsnKuvUGN", type: "multipleLookupValues" },
      "Custom Problem Statement and Solution Summary": { id: "fldgq9hGLwBQHYtqE", type: "multilineText" },
      "Use Intake Description for Summary": { id: "fld7dymDHI6sIoZGU", type: "checkbox" },
      "Executive Problem Statement and Solution": { id: "fldeq2QoexJSRyN5a", type: "formula" },
      "Project Status": { id: "fldibj8I0b793Wng8", type: "singleSelect", options: { choices: [{"name": "Proposal Created"}, {"name": "Proposal Accepted"}, {"name": "Proposal Signed"}, {"name": "Commencement Invoice Paid"}, {"name": "First Draft Delivered"}, {"name": "Project Accepted"}, {"name": "Completion Invoice Paid"}] } },
      "Got to Web Quote": { id: "fld7ewqo0gSNpxodo", type: "button" },
      "Client Request Change Feedback": { id: "fldmhU0JgdDFRhQnd", type: "multilineText" },
      "Proposal Type": { id: "fldHoa2I9wP6HeSZ9", type: "singleSelect", options: { choices: [{"name": "Airtable Solutions Proposal"}, {"name": "Web Development Proposal"}, {"name": "Airtable Solutions"}] } },
      "Total Cost": { id: "fldgiCZnsYGemOlqX", type: "rollup" },
      "Initial Invoice Amount": { id: "fldaXVDvg9tZtZH5p", type: "formula" },
      "Client Delivery Due Date": { id: "fldMC7hyVxocpwFUC", type: "date" },
      "Total Hours": { id: "fldWJzfMD3A1pPs0L", type: "rollup" },
      "Quote Expiration Date": { id: "fldRn0QjIM4aZg40D", type: "date" },
      "Payment Terms": { id: "fldECFZ2nrPPadt3I", type: "singleSelect", options: { choices: [{"name": "50% Deposit / 50% on Delivery"}, {"name": "Net 15"}, {"name": "Net 30"}, {"name": "Net 45"}, {"name": "Due on Receipt"}] } },
      "PandaDoc SOW ID": { id: "fld77uHFi4L7K5lbI", type: "singleLineText" },
      "PandaDoc SOW URL": { id: "fld7X8EdTOQqj2eM6", type: "url" },
      "PandaDoc SOW Status": { id: "fldqQlXCoYNVd5XLg", type: "singleSelect", options: { choices: [{"name": "Not Sent"}, {"name": "Draft"}, {"name": "Sent"}, {"name": "Viewed"}, {"name": "Signed"}, {"name": "Declined"}, {"name": "Expired"}] } },
      "SOW PDF Attachment": { id: "fldpn3IDvPti3Xa1p", type: "multipleAttachments" },
      "Project Overview": { id: "fldkJBFuh3sY2sksg", type: "richText" },
      "Recommended Approach": { id: "fld5OJeRzoQnYWVc7", type: "richText" },
      "Estimate Hours Range": { id: "fld0z4bdJ4CUD0I5N", type: "singleLineText" },
      "Estimate Cost Range": { id: "fldE1oet1NHlf5Gaf", type: "singleLineText" },
      "Prepared By Name": { id: "flds3UK5j9CErPCrm", type: "multipleLookupValues" },
      "Prepared By Email": { id: "fldoyNt87nbFflRrz", type: "multipleLookupValues" },
      "Signer Name": { id: "fldJQoq6suka5GO6o", type: "singleLineText" },
      "Signer Email": { id: "fldu5xGL9GCfUl44J", type: "email" },
      "Signature Image": { id: "fldAx7vInfivzWwZR", type: "multipleAttachments" },
      "Signed Date": { id: "fldSWDAfvHairoigV", type: "dateTime" },
      "Signer IP": { id: "fldsRt6kcMYJNPzpd", type: "singleLineText" },
      "Signer User Agent": { id: "fldeNvwRoCDvdIlj7", type: "multilineText" },
      "Documents needed for Proposal": { id: "fldNPHj10hrw6rg6d", type: "multipleAttachments" },
      "Recommended Approach Summary": { id: "fldsIw1h3eNDyu7IA", type: "multilineText" },
      "Quote Last Access": { id: "fldIYXqOtAyFEyH99", type: "dateTime" },
    },
  },
  Invoices: {
    id: "tblBrtvazPOkXrB80",
    name: "\u26aa\ufe0f Invoices",
    fields: {
      "Invoice Identifier": { id: "fldMmDXxwC2s9Ircd", type: "formula" },
      "Invoice ID": { id: "fldInKnMyrsoPutYz", type: "autoNumber" },
      "Invoice Description": { id: "fldATkZpdsRH8X50S", type: "multilineText" },
      "Form Submissions": { id: "fldPLYCBd9ICxh9RX", type: "multipleRecordLinks" },
      "Quotes": { id: "fldtSvQOJDsYfDoQl", type: "multipleRecordLinks" },
      "Form Submission (from Quotes)": { id: "fldxraNu5ZXGmGh0l", type: "multipleLookupValues" },
      "Invoice Source": { id: "fld213DzzWZRhrhHB", type: "singleSelect", options: { choices: [{"name": "Fiverr"}, {"name": "Stripe"}, {"name": "Other"}] } },
      "Fiverr Gig Link": { id: "fldMtI2Om7uAnQ0zC", type: "url" },
      "Fiverr User Account": { id: "fldzFGHp4xidgDKsh", type: "singleLineText" },
      "Fiverr Status": { id: "fldkDdhCcOXTI5Ryc", type: "singleSelect", options: { choices: [{"name": "Gig Pending Acceptance"}, {"name": "Gig Accepted"}, {"name": "Gig Funds Cleared"}] } },
      "Fiverr Amount": { id: "fldV3UVXl9rwHB4vc", type: "currency" },
      "Date": { id: "fldoUM33V6ol28rPy", type: "date" },
      "Invoice Amount": { id: "fldjH62YX2hE2ZzKd", type: "currency" },
      "Overhead (20%)": { id: "fldr5u7z4pAk072Pg", type: "formula" },
      "Engineer 60%": { id: "fld4Qdxf1gsaJsNMz", type: "formula" },
      "BA 20%": { id: "fldbT6ZfeorXb2R9S", type: "formula" },
      "Invoice Payer": { id: "fldZYLy6CKx14suH0", type: "multipleRecordLinks" },
      "Stripe Customer ID (from Invoice Payer) 2": { id: "fld9UOSADP2h6b28B", type: "multipleLookupValues" },
      "Client Stripe Status": { id: "fldbZptSbGyvNuJS0", type: "formula" },
      "BA": { id: "fldrJSvwODrB9JJGw", type: "multipleCollaborators" },
      "Engineer": { id: "fldBRUVh19FSXQooP", type: "multipleCollaborators" },
      "Stripe Customer ID (from Invoice Payer)": { id: "fldzRDsXQP7hXsJBP", type: "multipleLookupValues" },
      "Create and Send Invoice": { id: "fldwGNXVXM9wEhvZ0", type: "checkbox" },
      "Invoice Stripe ID": { id: "flds7oieRsOAmfSD2", type: "singleLineText" },
      "Invoice Stripe Link": { id: "fldtsItvlWJ9SGWDr", type: "url" },
      "Retainer": { id: "fldGUsMocwG70hVcC", type: "multipleRecordLinks" },
      "Subscription Stripe Link": { id: "fldD8M4AKbBpADsqb", type: "url" },
      "Subscription Stripe ID": { id: "fldYN4JNqDKvofHF2", type: "singleLineText" },
      "Invoice Type": { id: "fld04kdnJ7Eu85f9f", type: "singleSelect", options: { choices: [{"name": "One-time"}, {"name": "Recurring"}, {"name": "Payment Plan"}] } },
      "Invoice Status": { id: "fldQTgMQ7RfXDzStJ", type: "singleSelect", options: { choices: [{"name": "open"}, {"name": "paid"}, {"name": "past due"}, {"name": "failed"}, {"name": "unsent"}, {"name": "sent"}, {"name": "Canceled"}, {"name": "Refunded"}, {"name": "void"}, {"name": "subscribed"}, {"name": "send subscription link"}] } },
      "Payment Plan - Number of Payments": { id: "fldnTt6oPseXcokBw", type: "number" },
      "Payment - Plan - Frequency": { id: "fldO2gxAKE6zlf0Rz", type: "singleSelect", options: { choices: [{"name": "weekly"}, {"name": "biweekly"}, {"name": "monthly"}] } },
      "Discount %": { id: "fldtDDqZWHsi1EzIS", type: "percent" },
      "Discount Length (number of payments)": { id: "fldEu2QMTRjUSzJbm", type: "number" },
      "Apply Discount?": { id: "fldsSgrMlftS0DWYg", type: "formula" },
      "Need Client Approval for Subscription Payment?": { id: "fldHUjQDVUsowKE7d", type: "singleSelect", options: { choices: [{"name": "Yes"}, {"name": "No"}] } },
      "Approved by Airvues Leadership": { id: "fldJ6YQKsHGjHNYNj", type: "checkbox" },
      "Invoice Status Last Modified": { id: "fldi5X9PbQfXEKJJa", type: "lastModifiedTime" },
      "Time to check": { id: "fld8jFhpgcge558Ni", type: "formula" },
      "Overhead": { id: "fldUzVrd7But4CzWA", type: "singleCollaborator" },
      "Comments": { id: "fld2VAdpO46JDO7dH", type: "multilineText" },
      "Initial Invoice": { id: "fld9rxr8IdKl4lOpj", type: "checkbox" },
      "Team Payments": { id: "fldHhloz68cQYjUJg", type: "multipleRecordLinks" },
      "Amount Paid to BA": { id: "fldpzt7EFZ5SMTuUE", type: "rollup" },
      "Amount Paid to Engineers": { id: "fld3FHsZCVuTQgO9l", type: "rollup" },
      "BA Payment Check": { id: "fld8eLRS2cZAR1JWf", type: "formula" },
      "Engineer Payment Check": { id: "fldo6XgocDo8cD8Wj", type: "formula" },
      "BA Payment Status": { id: "fldxQy1mEQq23DO5l", type: "rollup" },
      "Engineer Payment Status": { id: "fldVeWprvUXnqQyU5", type: "rollup" },
      "Retainer/Payment Plan Count of Payments": { id: "fld3Qma1QzSd8LJG5", type: "count" },
      "Trigger Discount Deletion": { id: "fldM4IdWVMGSFk8dU", type: "formula" },
      "Retainer Individual Invoices": { id: "fldk5HZPAEynVT5gI", type: "multipleRecordLinks" },
      "Days to Next Payment": { id: "fldByLLlmSp9Y58Xr", type: "formula" },
      "Temp": { id: "fldoamiYprL7PWEF0", type: "checkbox" },
      "recordID": { id: "fld5gMuuZAN7CPNDi", type: "formula" },
      "Stripe Invoice": { id: "fldEECamMqCOU2woV", type: "button" },
      "Created By": { id: "fldP83fh3wrunoDo4", type: "createdBy" },
      "Created": { id: "fld7swQFu5P8NQqE5", type: "createdTime" },
      "Days to Next Payment Plan": { id: "fld5ZincRaWg4zSeB", type: "formula" },
      "Calculation": { id: "fldvjpWNkqaMmJgiN", type: "formula" },
      "Payment Plan - Payment Amount": { id: "fldG4C9xCig1yt56c", type: "formula" },
      "\u26aa\ufe0f Internal Commission Tracker": { id: "fldL8EWSNLE6E4H8e", type: "multipleRecordLinks" },
      "Total Airvues Margin Profit": { id: "fld1pAOqg2zwCi41s", type: "rollup" },
      "Admins (from Form Submission) (from Quotes)": { id: "fldzmGOrySxgnvvFA", type: "multipleCollaborators" },
      "Filter Field for Legacy way of doing invoices (do not delete in 2027)": { id: "fldSitmTbxOtb5My8", type: "checkbox" },
    },
  },
  InternalCommissionTracker: {
    id: "tblZq696m9iqO30ps",
    name: "\u26aa\ufe0f Internal Commission Tracker",
    fields: {
      "Commission ID & Team Member": { id: "fldeCJusbdA1E108A", type: "formula" },
      "ID": { id: "fldWagcC78ErowBbH", type: "autoNumber" },
      "Team Member": { id: "fldP8W94GpS3QZAq8", type: "singleCollaborator" },
      "Function": { id: "fldejPqrKHcq9HX56", type: "singleSelect", options: { choices: [{"name": "Engineer"}, {"name": "BA"}] } },
      "Payment Type": { id: "fldtnDXPm8ImquRV6", type: "singleSelect", options: { choices: [{"name": "Hours"}, {"name": "Percentage"}, {"name": "Lump Sum"}] } },
      "Percentage": { id: "fldk09kIHgCwa70Um", type: "percent" },
      "Amount": { id: "fldsZUAoLBEWs1Pml", type: "currency" },
      "Invoice": { id: "fldirPyKLf9dwpxIn", type: "multipleRecordLinks" },
      "Invoice Status (from Invoice)": { id: "fldGTqN1JyyMGiQil", type: "multipleLookupValues" },
      "Approved by Airvues Leadership (from Invoice)": { id: "fldJf1UdrSBZXeHzW", type: "multipleLookupValues" },
      "Invoice Amount (from Invoice)": { id: "fldj4uW10NRUmzKYX", type: "multipleLookupValues" },
      "Total Amount": { id: "fldBRmbPiKMfiHEBo", type: "formula" },
    },
  },
  Products: {
    id: "tblqhGm5GphLg982W",
    name: "\ud83d\udfe2 Products",
    fields: {
      "Product Identifier": { id: "flddQnoa8GRVX8xzg", type: "formula" },
      "Codename": { id: "fldplONZnsa4otPPe", type: "singleLineText" },
      "Product Record ID": { id: "fldCYPWRIm4JbaJgg", type: "formula" },
      "Name": { id: "fldW3r7lvZuHS9f45", type: "singleLineText" },
      "Company": { id: "fldriXsoKKWFRQ0Bx", type: "multipleRecordLinks" },
      "Product Owner [Lead]": { id: "fldDSQmGCq1h4WnRO", type: "multipleRecordLinks" },
      "Sagas": { id: "fld2EuMC1MXPWlveI", type: "multipleRecordLinks" },
      "Company (from Product Owner)": { id: "fld0Wvol3TD7sXNRm", type: "multipleLookupValues" },
      "\u274cProjects (old)": { id: "fld1tBldQd8dEvbeq", type: "singleLineText" },
      "Agreed Hourly Rate (from Companies) (from Product Owner [Lead])": { id: "fldXsGnO0H9ozvavS", type: "multipleLookupValues" },
      "Contract Type (from Company) (from Product Owner [Lead])": { id: "fldUPjK6odTOmXe7O", type: "multipleLookupValues" },
      "Production Status": { id: "fldtAAHmAqfbXS6FC", type: "singleSelect", options: { choices: [{"name": "New"}, {"name": "In Development"}, {"name": "Ready for Deployment"}, {"name": "Deployed \u2013 In Testing"}, {"name": "Active \u2013 Live"}, {"name": "Active \u2013 Monitored"}, {"name": "Active \u2013 Not Monitored"}, {"name": "Maintenance Mode"}, {"name": "Archived"}] } },
      "Epics (from Sagas)": { id: "fldz3xNl8vIsv4lec", type: "multipleLookupValues" },
      "Product Description": { id: "fldNgiICRY3iiheqG", type: "richText" },
      "Stories (from Epics) (from Sagas)": { id: "fldJgm3ejTQRuYnLD", type: "multipleLookupValues" },
      "Agenda": { id: "fldR24FtBesR5vWKn", type: "multipleRecordLinks" },
    },
  },
  Sagas: {
    id: "tblkb03JiSuxi7Hkf",
    name: "\ud83d\udfe2 Sagas",
    fields: {
      "Saga ID": { id: "fldiIi67BgRQHRQ71", type: "formula" },
      "Saga Record ID": { id: "fldKmFy2iFcxIA9xg", type: "formula" },
      "Saga Name": { id: "fldRYU9ZF5eFV9ui3", type: "singleLineText" },
      "Products": { id: "fld3eqyJaQZUUx71m", type: "multipleRecordLinks" },
      "Epics": { id: "fld1W9a94Tx0cld5l", type: "multipleRecordLinks" },
      "Description": { id: "fld7sfbR1spRe4UYX", type: "multilineText" },
      "Status": { id: "fldx0RpPxfG8hv79p", type: "singleSelect", options: { choices: [{"name": "Planned"}, {"name": "In Progress"}, {"name": "On Hold"}, {"name": "Completed"}, {"name": "Cancelled"}] } },
      "Priority": { id: "fldI1vhyVFIknhBLk", type: "singleSelect", options: { choices: [{"name": "Urgent"}, {"name": "High"}, {"name": "Medium"}, {"name": "Low"}] } },
      "Progress": { id: "fldU0v94lqx0kmxCX", type: "percent" },
      "Stories (from Epics)": { id: "fldRRrHKK3ZWC4Yvv", type: "multipleLookupValues" },
    },
  },
  Epics: {
    id: "tbl0VEFw95zHBUK7s",
    name: "\ud83d\udfe2 Epics",
    fields: {
      "Epic ID": { id: "fldZGEXtNgX0UBhXa", type: "formula" },
      "Epic Record ID": { id: "fldcRvkUb1jx7NApT", type: "formula" },
      "Epic Name": { id: "fldTghhvs9wguUgGA", type: "singleLineText" },
      "Products": { id: "fld5TF6hKKYjF3DgT", type: "multipleLookupValues" },
      "Sagas": { id: "fldsF2zNBbOqgvXHV", type: "multipleRecordLinks" },
      "\u274c Client Requests (Old)": { id: "fldhtAWuCGXe8CEhd", type: "singleLineText" },
      "Description": { id: "fldY8BtiW1TD03PAf", type: "richText" },
      "Stories": { id: "fldF5mWkEwDwAludn", type: "multipleRecordLinks" },
      "Total Stories": { id: "fldwKTiwawWrTRFca", type: "count" },
      "Completed Stories": { id: "fldpEWkkL8yRKa9l4", type: "count" },
      "on Backlog": { id: "fldgmb74Z2Ql4NlwK", type: "count" },
      "on Intake": { id: "fldxWblTMj25NpFqW", type: "count" },
      "Assigned Stories": { id: "fldJdEbIi9PNrMRxQ", type: "count" },
      "Completion": { id: "fldDuCZvLOypJubI8", type: "formula" },
      "Epic Invoice": { id: "fldcqCYjj5hun1fMq", type: "rollup" },
      "Client": { id: "fldxAm95f3fzDY5zS", type: "multipleRecordLinks" },
    },
  },
  Stories: {
    id: "tblgd7iKw2KdPBkn2",
    name: "\ud83d\udfe2 Stories",
    fields: {
      "Story ID": { id: "fldu9QJjbcTt2tdRu", type: "formula" },
      "Epic": { id: "fldv4E8RMtY8CytSr", type: "multipleRecordLinks" },
      "Client (from Epic)": { id: "fldKu5ZvlODSKdcrh", type: "multipleLookupValues" },
      "Products": { id: "fldmm0YktUbLfw8XD", type: "multipleLookupValues" },
      "Sagas (from Epic)": { id: "fldG7lR2Wzuh3T7te", type: "multipleLookupValues" },
      "Story Record ID": { id: "fldknE4k0Bk5NXKF7", type: "formula" },
      "Story Name": { id: "fld7WhR7hOT5fB0in", type: "singleLineText" },
      "Description": { id: "fldp8gesIhkvtiTqZ", type: "richText" },
      "Hours": { id: "fldVsSECKTAmsd1N2", type: "number" },
      "Assignee": { id: "fldEY2784x4ueTtni", type: "multipleRecordLinks" },
      "Story Status": { id: "fldTNsiYuGhCVx7Vy", type: "singleSelect", options: { choices: [{"name": "Todo"}, {"name": "In progress"}, {"name": "QA Review"}, {"name": "Completed"}, {"name": "On Hold"}, {"name": "Incomplete"}, {"name": "Analysis Required"}, {"name": "Archived"}] } },
      "\ud83d\udcc6Sprints": { id: "fld4M1RwkvhsPlnuj", type: "multipleRecordLinks" },
      "Sprint Number (from \ud83d\udcc6Sprints)": { id: "fldHjCX8JgObHgQbG", type: "multipleLookupValues" },
      "Sprint Cap ID": { id: "fldw2GQG60GfzYysT", type: "formula" },
      "Sprint Status (from \ud83d\udcc6Sprints)": { id: "fldcbS3H9HiYNZoJE", type: "multipleLookupValues" },
      "Sprint Start (from \ud83d\udcc6Sprints)": { id: "fldcP7jcos9ClLE14", type: "multipleLookupValues" },
      "Sprint End (from \ud83d\udcc6Sprints)": { id: "fldXPenG2a2bjEmIn", type: "multipleLookupValues" },
      "Priority": { id: "fldglTb4b0Gwvv8WK", type: "singleSelect", options: { choices: [{"name": "Urgent"}, {"name": "High"}, {"name": "Medium"}, {"name": "Low"}] } },
      "Fully Scoped?": { id: "fldBH3hkrozc0pxxk", type: "singleSelect", options: { choices: [{"name": "Yes \ud83d\udfe2"}, {"name": "No \u274c"}] } },
      "\u2699\ufe0fIncomplete": { id: "fldmfCJ3WczoDo2WC", type: "checkbox" },
      "Link to Other Stories": { id: "fldXBy5xjrJ3TjJHq", type: "multipleRecordLinks" },
      "Next Sprint \ud83e\uddee (from \ud83d\udcc6Sprints)": { id: "fld81mVDil2E8eoqE", type: "multipleLookupValues" },
      "Fiverr Conversation History": { id: "fld5vp2wdnFt6dyoo", type: "multilineText" },
      "Client": { id: "fld8iY9Ok37WE1Nts", type: "multipleRecordLinks" },
      "Attachments": { id: "fld31eYKjEjMB7OQv", type: "multipleAttachments" },
      "Developer Notes": { id: "fldKau72dC1cCzeNZ", type: "multilineText" },
      "Developer Attachments": { id: "fldm0JvEFG9OMoxHO", type: "multipleAttachments" },
      "Hours Worked": { id: "fldAbpv9XTUFpkgHi", type: "number" },
      "Sprint Capacity": { id: "fldZgx0SwbS4ZnZMa", type: "multipleRecordLinks" },
      "Invoice": { id: "fld8wgKUiTPUu6ojD", type: "currency" },
      "Hours Logged": { id: "fldWxzhlmeLVg4o9W", type: "rollup" },
      " Budget % Used": { id: "fldNRRlkSEHmdSHBP", type: "formula" },
      "Budget Status": { id: "fldY3wopLfGpFuX2w", type: "formula" },
      "User (from Assignee)": { id: "fldKQIBgFRksqR9Pj", type: "multipleLookupValues" },
      "Invoices copy": { id: "fldXDD4FOmPFZkVMh", type: "singleLineText" },
      "Quote": { id: "fldxpgFFlCyqXXYcF", type: "multipleRecordLinks" },
      "Client Notes": { id: "fldvNXiWGb5Mu0xmC", type: "multilineText" },
      "Cost": { id: "fldKgQjIt5QiI7KB0", type: "currency" },
      "ID": { id: "fldy4b4PnNNGXkouC", type: "autoNumber" },
      "\ud83d\udd35 Time Entries": { id: "fldrz77Nu5Pbi4ucW", type: "multipleRecordLinks" },
      "Manual sort": { id: "fldepJFnkcijIEfqW", type: "manualSort" },
      "Phase": { id: "fldu8cAPCJbdDS6zb", type: "singleSelect", options: { choices: [{"name": "Phase 1"}, {"name": "Phase 2"}, {"name": "Phase 3"}] } },
    },
  },
  SprintCapacity: {
    id: "tbleikKz5Tt8tSc0J",
    name: "\ud83d\udfe2 Sprint Capacity",
    fields: {
      "Name": { id: "fldAz6Q689639ylPZ", type: "formula" },
      "People": { id: "fld6ZsfuwY4mbac4c", type: "multipleRecordLinks" },
      "Status (from People)": { id: "fldFrc3OgTrsGfVOa", type: "multipleLookupValues" },
      "Sprint": { id: "fldLZcf6MPNyGsRC4", type: "multipleRecordLinks" },
      "Stories": { id: "fldfTQb176VL2M9GC", type: "multipleRecordLinks" },
      "total hours committed": { id: "fldy8ZJXfITG3Ntn7", type: "number" },
      "Effort Estimate (Hr) (from Stories)": { id: "fldvLVs1gHXonD3X6", type: "rollup" },
      "Notes": { id: "fldrsXjbOPqoG2KKN", type: "singleLineText" },
      "Sprint Number (from Sprint)": { id: "fldwrdwtRsgm0IZep", type: "multipleLookupValues" },
      "Sprint Status (from Sprint)": { id: "fldtxZdm996ZyCzUm", type: "multipleLookupValues" },
    },
  },
  TeamTaskPayments: {
    id: "tblvzdxVq7drJtobt",
    name: "\ud83d\udd35 Team Task Payments",
    fields: {
      "Payment Job ID": { id: "fldwKOnImb0Xnzlxw", type: "autoNumber" },
      "Client Invoice": { id: "fld5M4m6N0ZRXQFGn", type: "multipleRecordLinks" },
      "Date (from Client Invoice)": { id: "fldRItOeChQKP6LrG", type: "multipleLookupValues" },
      "Year": { id: "fld7wLicR05QHVxzU", type: "formula" },
      "Form Submissions (from Client Invoice)": { id: "fldx6QHYmuqYJ6dWx", type: "multipleLookupValues" },
      "Invoice Payer (from Client Invoice)": { id: "fldbZbknOsEqGZoqL", type: "multipleLookupValues" },
      "Project": { id: "flddSeskUPaUzmRYV", type: "multipleLookupValues" },
      "Amount": { id: "fldu1wKXoUsz03APF", type: "currency" },
      "Date": { id: "fldoarbDiTmw4zmtR", type: "createdTime" },
      "Function": { id: "fldGkVpDaPtIYYWV1", type: "singleSelect", options: { choices: [{"name": "Engineer"}, {"name": "BA"}] } },
      "Payee": { id: "fldWfgR4RKJHqKtP6", type: "singleCollaborator" },
      "Status": { id: "fldTxHysl6xWQsyWz", type: "singleSelect", options: { choices: [{"name": "Needs Payment"}, {"name": "Paid"}] } },
      "Link to Expenses": { id: "fldrLGwAWY1h5r0VJ", type: "multipleRecordLinks" },
      "Status (from Link to Expenses)": { id: "fldXjmqWa24vmsw0w", type: "multipleLookupValues" },
      "Internal Team Member Account (from Link to Expenses)": { id: "fldkZAtaG66iN4Suj", type: "multipleLookupValues" },
      "Onboarding Status (from Internal Team Member Account) (from Link to Expenses)": { id: "fld0JnNO5AfQC64dc", type: "multipleLookupValues" },
      "Calculation": { id: "fldjLbsr8GSLKnlBV", type: "formula" },
      "Onboarding Portal Link (from Link to Expenses) copy": { id: "fldgv5FV294flqakb", type: "multipleLookupValues" },
      "Open URL": { id: "fldUKhysaJJkKHYyj", type: "button" },
      "Comments": { id: "fldEASdEkMbXgLHaX", type: "multilineText" },
      "Project #": { id: "fldVK4LESa71HNgcZ", type: "formula" },
      "Invoices copy": { id: "fldywO55bJRfK6qlC", type: "singleLineText" },
      "Invoice Source (from Client Invoice)": { id: "fldO4ngM0C3rbmZkP", type: "multipleLookupValues" },
      "Payment Status (from Link to Expenses)": { id: "fldkUwEQPghoiUqeU", type: "multipleLookupValues" },
      "Client": { id: "fldKk0W5i9iEOn5no", type: "formula" },
    },
  },
  Accounts: {
    id: "tblq1Sa3bCnP9QfAj",
    name: "\ud83d\udd35 Accounts",
    fields: {
      "Name": { id: "fld7oeyFGwuA1mMrA", type: "singleLineText" },
      "username": { id: "fldoo6QagEkzyjMrT", type: "multilineText" },
      "passcode": { id: "fld5gfSyWYrK9uHLM", type: "singleLineText" },
      "# of accounts": { id: "fldolow4OrpmC0mQG", type: "number" },
      "price": { id: "fldzeHTdMKPwGPBqO", type: "currency" },
      "frequency": { id: "fldSwTeTely3w3idV", type: "singleSelect", options: { choices: [{"name": "monthly"}, {"name": "quarterly"}, {"name": "yearly"}, {"name": "other"}, {"name": "na"}] } },
      "notes": { id: "fldiXe89uaqFqARqN", type: "richText" },
      "\u2699\ufe0f Software": { id: "fld1GYcJrAKScarNN", type: "multipleRecordLinks" },
      "URL (from \u2699\ufe0f Software)": { id: "fldvwvhR0c6oVeYJ9", type: "multipleLookupValues" },
      "Owner": { id: "fldbjybLapesVaf4f", type: "singleSelect", options: { choices: [{"name": "Airvues"}, {"name": "Client Owned"}] } },
      "Status": { id: "fld057DhwYWYsdro4", type: "singleSelect", options: { choices: [{"name": "Active"}, {"name": "Inactive"}, {"name": "Unknown"}] } },
      "URL": { id: "fldEvzY2Dwpf79aez", type: "url" },
    },
  },
  AirvuesExpenses: {
    id: "tblhQ9jkgVAuG97gg",
    name: "\ud83d\udd35 Airvues Expenses",
    fields: {
      "Expense ID": { id: "fld6HHa6Q6eQ7kQVi", type: "autoNumber" },
      "Expense Name": { id: "fldZuEcfy84IIosAO", type: "singleLineText" },
      "Internal Team Member Account": { id: "fldFxPqnKgZYEP8M6", type: "multipleRecordLinks" },
      "Internal Type (from Internal Team Member Account)": { id: "fldbGILCrmCO2wOC7", type: "multipleLookupValues" },
      "Onboarding Portal (from Internal Team Member Account)": { id: "fldOi9PbOskK1jGSJ", type: "multipleLookupValues" },
      "Onboarding Portal": { id: "fldWWMHCavTwIi4Ja", type: "button" },
      "Onboarding Status (from Internal Team Member Account)": { id: "fldmmh5zNYJ0UZONY", type: "multipleLookupValues" },
      "Stripe Account ID": { id: "fldfHaMEM2piI1xOG", type: "multipleLookupValues" },
      "Payee": { id: "fldiGL4uFvoh0sTgp", type: "singleCollaborator" },
      "Project # Rollup (from Team Payment Jobs)": { id: "fldtShiC8RsYcvCue", type: "rollup" },
      "Description": { id: "fldyO6iLVzQzp3vYN", type: "rollup" },
      "Amount": { id: "fldN8cxXF1NYbf85A", type: "currency" },
      "Date": { id: "fldtc8zSeDnNloZAV", type: "date" },
      "Year": { id: "fldV6123ZpQR51DjK", type: "singleSelect", options: { choices: [{"name": "2024"}, {"name": "2025"}, {"name": "#ERROR!"}, {"name": "2026"}] } },
      "Transaction Source": { id: "fldlIHjRkSb7U8o7Y", type: "singleSelect", options: { choices: [{"name": "Business Checking Account"}, {"name": "Business Credit Card"}, {"name": "Fiverr Balance"}, {"name": "Personal Apple Card"}, {"name": "Stripe Connect"}] } },
      "Ready to Pay": { id: "fld5rFaJC0ilWCe9Q", type: "checkbox" },
      "Type": { id: "fldTgcdQZR5NkYs0A", type: "singleSelect", options: { choices: [{"name": "Contractor Commissions"}, {"name": "Operating Expenses"}, {"name": "Not an Expense"}, {"name": "Salary"}] } },
      "Invoice/Receipt": { id: "fldor8bAjNd824B24", type: "multipleAttachments" },
      "Status": { id: "fldILjXt6QmeYixoX", type: "singleSelect", options: { choices: [{"name": "Paid"}, {"name": "Failed"}, {"name": "Pending"}] } },
      "Stripe Transfer ID": { id: "fldzI7Gz8UMid3zmC", type: "singleLineText" },
      "Error": { id: "fldPpO9SQ0Y9lmBuR", type: "multilineText" },
      "Paid At": { id: "fldd33w4X7zs3SW4R", type: "date" },
      "Team Payment Jobs": { id: "fldP2hIR5uQUfub7t", type: "multipleRecordLinks" },
      "Amount (USD)": { id: "fldQ8lN0T22Xsf7Hy", type: "rollup" },
      "Hour of Day": { id: "fldh0zCWEd9qfobk5", type: "formula" },
    },
  },
  Subscriptions: {
    id: "tblZnJdKLwgj5GMOb",
    name: "\ud83d\udd35 Subscriptions",
    fields: {
      "Name": { id: "fldd8ANcN1lbGGrmM", type: "singleLineText" },
      "Amount": { id: "fldDjfMoaPxgHbOFL", type: "currency" },
      "Source": { id: "fld5aB1PFrjXuQi7h", type: "singleSelect", options: { choices: [{"name": "Business Checking"}, {"name": "Business Credit Card"}] } },
      "Type": { id: "fldFITXqD72MKTm28", type: "singleSelect", options: { choices: [{"name": "Monthly"}, {"name": "Yearly"}] } },
      "Start Date": { id: "fldAUj1bsLvYMBffw", type: "date" },
      "End Date": { id: "fldlEnCPt43EnH1IW", type: "date" },
    },
  },
  TeamResourceAllocationDailyStandups: {
    id: "tbl5x2jqUPHcAoKci",
    name: "\ud83d\udd18 Team Resource Allocation & Daily Standups",
    fields: {
      "Name": { id: "fldczCoQvABrS6MK0", type: "formula" },
      "Date": { id: "fldTYVofSM3pjUspv", type: "createdTime" },
      "Daily Report": { id: "flddIZ4OQQhG8WbF6", type: "multipleRecordLinks" },
      "Team Member": { id: "fldRovFVHwjvnOmeh", type: "multipleRecordLinks" },
      "Bandwidth Available Hours This Week": { id: "fldDGwb78pNziVVtO", type: "number" },
      "Projects you're working on": { id: "fldFbfIU1Pa7JlCzv", type: "multipleRecordLinks" },
      "This Week's Workload Hours": { id: "fld8sIj9cAGz68ZUk", type: "number" },
      "Yesterday Notes": { id: "flddm0iwiAh8TgHk0", type: "multilineText" },
      "Today Notes": { id: "fldLR4VFB9OwQsHkF", type: "multilineText" },
      "On Pace to Complete Project On Time": { id: "flddBeJBwHP8900ub", type: "singleSelect", options: { choices: [{"name": "Absolutely!"}, {"name": "Looking good"}, {"name": "Maybe"}, {"name": "Need help!"}] } },
      "Blockers": { id: "fld6LPQU2qgNzNAwx", type: "multilineText" },
      "On Pace": { id: "fldKBKEFIyQIz06pN", type: "formula" },
      "In Between Engagement Notes": { id: "fld6ZZ9I7RPDiLS8b", type: "multilineText" },
      "Date Formatted": { id: "fldTROBqevLbH0fXc", type: "formula" },
    },
  },
  DailyReport: {
    id: "tbluN9YQjm0X3ju1n",
    name: "\ud83d\udd18 Daily Report",
    fields: {
      "Name": { id: "fldVUU2HOjdHitWAY", type: "singleLineText" },
      "Team Resource Allocation & Daily Standups": { id: "fldPYcPBSUQ6DNgCO", type: "multipleRecordLinks" },
      "Projects you're working on Rollup (from Team Resource Allocation & Daily Standups)": { id: "fldQYrUN4ZcoBhqZi", type: "rollup" },
      "Bandwidth Available Rollup (from Team Resource Allocation & Daily Standups)": { id: "fldrBPSNlAbj17Bny", type: "rollup" },
    },
  },
  ClientFeedback: {
    id: "tbl4GlNscZUI3XXwU",
    name: "\ud83d\udd18 Client Feedback",
    fields: {
      "Feedback ID": { id: "fld5NEmYkyngGRGIj", type: "autoNumber" },
      "Client Intake": { id: "fldkupICfWx0YAPxs", type: "multipleRecordLinks" },
      "Testimonial": { id: "fldbCWY3PwpC3oVAl", type: "richText" },
      "How can we improve?": { id: "fldPAbi656nI47ysh", type: "multilineText" },
      "Overall Review": { id: "fldoaqHFvhedHfRd6", type: "rating" },
      "Follow up for success story?": { id: "fldE8lAJwVRbi8ezG", type: "singleSelect", options: { choices: [{"name": "Yes"}, {"name": "No"}] } },
      "Full Name": { id: "fldZmoWKhl61GbOYJ", type: "singleLineText" },
      "Title": { id: "fldUAcX7ivSuJxiM7", type: "singleLineText" },
      "Company": { id: "fldAWOaGAiiXK7l1E", type: "singleLineText" },
      "ProjectNumber": { id: "fldYRy4MYEzEpcJoW", type: "singleLineText" },
    },
  },
  Sprints: {
    id: "tblixAL658VYnMKOz",
    name: "\u2699\ufe0f Sprints",
    fields: {
      "Sprint Name": { id: "fldltrUmRkfSHQmb2", type: "formula" },
      "Name Override": { id: "fldvGUEZRdCqrOd8X", type: "singleLineText" },
      "Sprint Number": { id: "fldJI1kBu5O6RfnlY", type: "number" },
      "Next Sprint": { id: "fldz0XuQ2MRyvpgSp", type: "formula" },
      "Sprint Status": { id: "fldR2ssCnqVKFPePZ", type: "singleSelect", options: { choices: [{"name": "In Progress"}, {"name": "Done"}, {"name": "Next"}] } },
      "Sprint Start": { id: "fldCAIm4fGYyXwK6T", type: "date" },
      "Sprint End": { id: "fldTmn12p4JSUmzvi", type: "formula" },
      "Next Sprint \ud83e\uddee": { id: "fldh9VBrZmlwRnEv8", type: "formula" },
      "Next Sprint \ud83e\uddee END": { id: "fldv1SjgJOPJGxZEr", type: "formula" },
      "Stories": { id: "fldaFhSYg4erPS5ke", type: "multipleRecordLinks" },
      "Created By": { id: "fldIJhYc2OyLJBUHg", type: "createdBy" },
      "Created": { id: "fldxlJVjLbUdOCbJy", type: "createdTime" },
      "Goals": { id: "fldaEiv9Ti5TO1b8n", type: "richText" },
      "Last Modified By": { id: "fld78YiecsvJk2mNY", type: "lastModifiedBy" },
      "Sprint Goals": { id: "fldx0AxVIhA4bORaG", type: "singleLineText" },
      "Transactional Sprint Log": { id: "fldO6qW0yXSktgcIU", type: "multipleRecordLinks" },
    },
  },
  Companies: {
    id: "tblQ3hxcIEUQPLN6f",
    name: "\u2699\ufe0f Companies",
    fields: {
      "Name": { id: "fldtSTbJ7UpZ5zhwW", type: "singleLineText" },
      "Company ID": { id: "flduQrOv5aeSTAvB1", type: "formula" },
      "Website": { id: "fldLBiRGOnuFRtBRB", type: "url" },
      "Business Description": { id: "fldyJoXNF3vfmOPxV", type: "aiText" },
      "Client List (Employees)": { id: "fld3dPOTRGyV9LRru", type: "multipleRecordLinks" },
      "\ud83d\udce5 Intake Queue [WIP]": { id: "fldgPnAJtLt0qsfUp", type: "singleLineText" },
      "Drive Folder": { id: "fld7R85ytieKfGp2C", type: "url" },
      "Miro Folder": { id: "fld37Ul8kO9AvLigX", type: "url" },
      "Created": { id: "fldWdJG4VDlpf1cYh", type: "createdTime" },
      "Client Required Agreements": { id: "fld90cNV36F4nVJ0P", type: "multipleAttachments" },
      "Airvues Terms of Service": { id: "fldztCIuWeFIlIfTh", type: "multipleAttachments" },
      "Contract Type": { id: "fldZ0xEBPUhbDQAow", type: "singleSelect", options: { choices: [{"name": "Lump Sum"}, {"name": "Hourly"}, {"name": "Membership"}] } },
      "Hourly Rate": { id: "fldt9Y9QqxzwxfS8K", type: "currency" },
      "Preferred Business": { id: "fldFc0koyQLJXXlu9", type: "singleSelect", options: { choices: [{"name": "Fiverr"}, {"name": "Off-the-Grid"}] } },
      "Logo": { id: "fld9dHkYbNyG4JZPX", type: "multipleAttachments" },
      "Has NDA?": { id: "fldqzOorGYE9oq3Ey", type: "checkbox" },
      "Form Submissions": { id: "fldLYFIwLMQk8tj2E", type: "multipleRecordLinks" },
      "\ud83d\udcf1Products": { id: "fld7ef1ScZYy5s5lk", type: "multipleRecordLinks" },
      "Engagement Frequency": { id: "fldUJ3OQGsBrIqsoO", type: "singleSelect", options: { choices: [{"name": "Active"}, {"name": "Occasional"}, {"name": "Iddle"}, {"name": "Lost"}, {"name": "New"}, {"name": "Archived"}] } },
      "Google Chat": { id: "fldhvEh5BSOxMP0KF", type: "url" },
      "Quotes": { id: "fldc7YiSzBzIEWLA8", type: "singleLineText" },
      "Legal Agreement - Part 1": { id: "fldjUx41mZLk1qLnl", type: "formula" },
      "Legal Agreement - Part 2": { id: "fld3SIYSeZpvJ8470", type: "formula" },
      "Media Assets": { id: "fldWenrrEtJuQQjZ9", type: "singleLineText" },
      "Attachments (from Media Assets)": { id: "fldFHSJvNe6etyXwH", type: "multipleLookupValues" },
      "Legal Address": { id: "fld4d2HGpPFxQLSMR", type: "multilineText" },
    },
  },
  People: {
    id: "tbl9wvZY9M7Y7hcf1",
    name: "\u2699\ufe0f People",
    fields: {
      "Person Identifier": { id: "fldSkgDMDkmC4EjHl", type: "formula" },
      "Unique Form URL": { id: "fldFOOMPJfNv73z03", type: "formula" },
      "Unique Client Record ID": { id: "fld6Hl1jGA2JVosqw", type: "formula" },
      "(deprecated) Client Status": { id: "fldhNSOZVxmq4H2pE", type: "singleSelect", options: { choices: [{"name": "New Client"}, {"name": "Active Client"}, {"name": "Inactive Client"}, {"name": "Lost Client"}] } },
      "Company": { id: "fldgpP2EeHtpoGAUk", type: "multipleRecordLinks" },
      "Create Customer Account in Stripe": { id: "fldM0YqIC3eApvhMK", type: "checkbox" },
      "Stripe Customer ID": { id: "fldnzYameBLC4hsBf", type: "singleLineText" },
      "VIP Client": { id: "fldFcz80qqv1TKyep", type: "checkbox" },
      "First Name": { id: "fld3C0D7SplZvljA7", type: "singleLineText" },
      "Full Name": { id: "fld2zHeNQMQjFKjB1", type: "formula" },
      "Last Name": { id: "fldjFvZfUOmfQoEiI", type: "singleLineText" },
      "Fiverr Account": { id: "fldlfAH3o3H46zcyn", type: "singleLineText" },
      "Primary Email": { id: "fld211B6UtbWr5c3f", type: "email" },
      "Phone Number": { id: "fldPxqlvYUjkB9eMP", type: "phoneNumber" },
      "Agreed Hourly Rate (from Companies)": { id: "fldMLG91S896DqLZH", type: "multipleLookupValues" },
      "Products": { id: "fldBCcyAmmQp4NvYK", type: "multipleRecordLinks" },
      "Country": { id: "fldpEJGaBRsMPxKTg", type: "multipleRecordLinks" },
      "Area Code": { id: "flduIoIcEvw578CNK", type: "multipleLookupValues" },
      "\ud83d\uddd3\ufe0f Stories": { id: "fldIFrEkvyK8lyCG1", type: "multipleRecordLinks" },
      "Contract Type (from Company)": { id: "fldvw378fhIGiD69j", type: "multipleLookupValues" },
      "Role": { id: "fldzj24tp7ayElqOJ", type: "singleLineText" },
      "Client Comments": { id: "fldM8DHbyz6jhmEKb", type: "richText" },
      "Interest": { id: "fld43EHPYVpsStBx0", type: "singleSelect", options: { choices: [{"name": "High"}, {"name": "Low"}] } },
      "Power": { id: "fld0gXkkBBeKE18TM", type: "singleSelect", options: { choices: [{"name": "High"}, {"name": "Low"}] } },
      "Stakeholder Priority": { id: "fldqytqdN9sK9zZ5I", type: "formula" },
      "Form Submission | \ud83d\udc64 Clients": { id: "fldVUPZqrghLy2sO7", type: "multipleRecordLinks" },
      "Airtable Account": { id: "fldeo2BqLzQ5xfiXx", type: "multipleCollaborators" },
      "Type": { id: "fldeQaa8IgkhQM9EU", type: "singleSelect", options: { choices: [{"name": "Internal"}, {"name": "External"}, {"name": "External client/partner"}, {"name": "Internal team member"}] } },
      "Status": { id: "fldVHzJogxKQDkndc", type: "singleSelect", options: { choices: [{"name": "Active"}, {"name": "Onboarding"}, {"name": "Innactive"}, {"name": "Unknown "}, {"name": "Former"}] } },
      "Stories": { id: "fldK9ddGoafIV2Epf", type: "multipleRecordLinks" },
      "Quotes": { id: "flde5APUJeGx96jXL", type: "multipleRecordLinks" },
      "Intake Proposals": { id: "fldzA8qUJ2jklFzJ9", type: "multipleRecordLinks" },
      "Form (from Intake Proposals)": { id: "fldA6PeUH7LBBMr39", type: "multipleLookupValues" },
      "Invoices": { id: "fldKgSW6a7IEEvJJW", type: "multipleRecordLinks" },
      "Transactional Sprint Log": { id: "fld2ZeVU0drRFll9U", type: "multipleRecordLinks" },
      "Quotes [Prepared for]": { id: "fldtGwrzEKTa5USKI", type: "multipleRecordLinks" },
      "Form Submissions | Submitter": { id: "fldFi2CuCljkjCFu6", type: "multipleRecordLinks" },
      "Form Submissions | Engineer Assigned": { id: "fldSgALdGSsAjxtqI", type: "multipleRecordLinks" },
      "Agenda | Creator": { id: "fldXslgnHrZl6c9oB", type: "multipleRecordLinks" },
      "Agenda | Attendees": { id: "fldFSwYnq7ZG752uh", type: "multipleRecordLinks" },
      "Epics": { id: "fldWQVm0EfXxEVXD7", type: "multipleRecordLinks" },
      "Team Resource Allocation & Daily Standups": { id: "fldSUOmbCIvKQptX8", type: "multipleRecordLinks" },
      "Slack User name": { id: "fldFGGWE0yqhwDgCw", type: "singleLineText" },
      "Intake ID (from Form Submissions | Engineer Assigned)": { id: "fld3zXKSwtvznP4Q9", type: "multipleLookupValues" },
      "Stripe Account ID": { id: "fldkNDvNYYxtzJRZM", type: "singleLineText" },
      "Onboarding Link": { id: "fldhkmSGouLk8byQx", type: "url" },
      "Onboarding Status": { id: "fldKPc9g32xxABQA3", type: "singleLineText" },
      "Send Onboarding": { id: "fldpGxOxwh2o2F8OH", type: "checkbox" },
      "Hour": { id: "fldDMjn2ke4ESwk3f", type: "formula" },
      "\ud83d\udd35 Airvues Expenses": { id: "fldPvUj6oshlUeDMY", type: "multipleRecordLinks" },
      "Onboarding Portal": { id: "fldSqzzGIYnQa70wW", type: "button" },
      "If on mobile, here is the link": { id: "fldLdGWDL61qlO7tX", type: "formula" },
      "Country Code": { id: "fld1kDGvy8nhCzzE1", type: "multipleLookupValues" },
      "\ud83d\udd35 Time Entries": { id: "fldF0nB5dcbZRlIra", type: "multipleRecordLinks" },
      "Internal Type": { id: "fldsUsm12jA9Ww2j8", type: "singleSelect", options: { choices: [{"name": "Employee"}, {"name": "Contractor"}] } },
      "Home Address": { id: "fldRxyfFHyo7RPvCC", type: "multilineText" },
      "Start Date": { id: "fldoUlU64IWJcRxNj", type: "date" },
      "Offer Date": { id: "fldY7udBJEkcSJzY2", type: "date" },
      "Reporting Manager": { id: "fldtjhYgQ40yXBFoN", type: "multipleRecordLinks" },
      "From field: Reporting Manager": { id: "fldJf5flFK4Z29TOP", type: "multipleRecordLinks" },
      "Comp Type": { id: "fldL5YBGLWNrn7q3N", type: "singleSelect", options: { choices: [{"name": "Hourly"}, {"name": "Monthly"}, {"name": "Per-task"}, {"name": "Equity"}] } },
      "Comp Amount": { id: "fldGdsKqzf1q4SHRM", type: "currency" },
      "Comp Currency": { id: "fldLmRUCLGeJUf1ll", type: "singleSelect", options: { choices: [{"name": "USD"}, {"name": "EUR"}, {"name": "MXN"}] } },
      "Equity Percentage": { id: "fldkqEP4H4L8Axmrw", type: "percent" },
      "Equity Vesting Terms": { id: "fldmmCNDmyIF3lWjz", type: "multilineText" },
      "Pay Frequency": { id: "fldYoAvR7VjhwwAo7", type: "singleSelect", options: { choices: [{"name": "Per Sprint"}, {"name": "Monthly"}, {"name": "Bi-weekly"}, {"name": "Per-task"}] } },
      "PandaDoc Offer ID": { id: "fldHPkTVAZkUAWZ0Q", type: "singleLineText" },
      "PandaDoc Offer URL": { id: "fldBIhrm1xzXUluiZ", type: "url" },
      "PandaDoc Offer Status": { id: "fld2D1ua890gRfvlJ", type: "singleSelect", options: { choices: [{"name": "Not Sent"}, {"name": "Draft"}, {"name": "Sent"}, {"name": "Viewed"}, {"name": "Signed"}, {"name": "Declined"}, {"name": "Expired"}] } },
      "Signed Offer PDF": { id: "fldJxYXpzaviNCTCV", type: "multipleAttachments" },
      "\u26aa\ufe0f Leads": { id: "fldISlK7qaJ9FRvvt", type: "multipleRecordLinks" },
    },
  },
  TimeEntries: {
    id: "tblKfmzZ0LtndU0CO",
    name: "\ud83d\udd35 Time Entries",
    fields: {
      "Entry Name": { id: "fldjJhwlzm1GY0CGa", type: "formula" },
      "Date": { id: "fldVp9Uci1DsylGXZ", type: "date" },
      "Hours": { id: "fldLHg6HBVu1oo7j1", type: "number" },
      "Notes": { id: "fldYcwTJW1TdxaXz2", type: "multilineText" },
      "Billable": { id: "fld1PP1smoJvWULXO", type: "checkbox" },
      "Person": { id: "fldvI2jRXrMd6o7aw", type: "multipleRecordLinks" },
      "Story": { id: "fldVl8OA7itxt0dW7", type: "multipleRecordLinks" },
      "Created": { id: "fldOD77ZSj4tebOrF", type: "createdTime" },
      "Last Modified": { id: "fldvTN6qSy2DmTDv1", type: "lastModifiedTime" },
      "Created By": { id: "flda9MXxabp9G2IHQ", type: "createdBy" },
    },
  },
} as const;

export type TableKey = keyof typeof Tables;

// Convenience alias
export const T = Tables;
