// Regenerates lib/schema.ts from the live Airtable Meta API.
//
//   node scripts/regenerate-schema.mjs          # writes lib/schema.ts
//   node scripts/regenerate-schema.mjs --check  # prints drift, writes nothing
//
// The KEY_OVERRIDES map below pins the `Tables.<Key>` names that existing code
// already imports. Never rename one of those keys — it silently breaks every
// call site. New tables get a key derived from their display name.
//
// Verify afterwards with: npm run verify-schema && npx tsc --noEmit

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..");
const OUT = join(REPO, "lib", "schema.ts");

const BASE_ID = process.env.AIRTABLE_BASE_ID || "app4vhhWMbRFOloOU";

function loadToken() {
  if (process.env.AIRTABLE_TOKEN) return process.env.AIRTABLE_TOKEN;
  try {
    const env = readFileSync(join(REPO, ".env.local"), "utf8");
    const m = env.match(/^AIRTABLE_TOKEN=(.+)$/m);
    if (m) return m[1].trim();
  } catch {
    /* no .env.local */
  }
  return null;
}

const TOKEN = loadToken();
if (!TOKEN) {
  console.error("AIRTABLE_TOKEN not set (env or .env.local).");
  process.exit(1);
}

// Table id -> the exact `Tables.<Key>` name that existing code imports.
// Adding a table here is safe; changing an existing value is not.
const KEY_OVERRIDES = {
  tbldeKGlLgRWSIzTh: "FormSubmissions",
  tblpOwt2GB1YE2bm3: "Leads",
  tbldBIfAeRAunipbk: "Quotes",
  tblBrtvazPOkXrB80: "Invoices",
  tblZq696m9iqO30ps: "InternalCommissionTracker",
  tblqhGm5GphLg982W: "Products",
  tblkb03JiSuxi7Hkf: "Sagas",
  tbl0VEFw95zHBUK7s: "Epics",
  tblgd7iKw2KdPBkn2: "Stories",
  tbleikKz5Tt8tSc0J: "SprintCapacity",
  tblvzdxVq7drJtobt: "TeamTaskPayments",
  tblq1Sa3bCnP9QfAj: "Accounts",
  tblhQ9jkgVAuG97gg: "AirvuesExpenses",
  tblZnJdKLwgj5GMOb: "Subscriptions",
  tbl5x2jqUPHcAoKci: "TeamResourceAllocationDailyStandups",
  tbluN9YQjm0X3ju1n: "DailyReport",
  tbl4GlNscZUI3XXwU: "ClientFeedback",
  tblixAL658VYnMKOz: "Sprints",
  tblQ3hxcIEUQPLN6f: "Companies",
  tbl9wvZY9M7Y7hcf1: "People",
  tbliI4lRYA5AlpEzH: "ProjectLog",
  tblKfmzZ0LtndU0CO: "TimeEntries",
  // Retainer portal (added 2026-08-06)
  tblT6U9M9EFa4lKu0: "RetainerTiers",
  tblRBsPqSvzvAuSyY: "RetainerRequests",
  tblIdtmSzkerb9xUS: "RetainerRequestComments",
};

// Strip emoji/punctuation from a display name and PascalCase what's left.
function deriveKey(name, used) {
  let key = name
    .replace(/[^\p{L}\p{N} ]/gu, " ")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  if (!key || /^\d/.test(key)) key = `Table${key}`;
  let candidate = key;
  let n = 2;
  while (used.has(candidate)) candidate = `${key}${n++}`;
  return candidate;
}

// Only these field types carry choices worth pinning in the generated file.
const CHOICE_TYPES = new Set(["singleSelect", "multipleSelects"]);

const resp = await fetch(`https://api.airtable.com/v0/meta/bases/${BASE_ID}/tables`, {
  headers: { Authorization: `Bearer ${TOKEN}` },
});
if (!resp.ok) {
  console.error(`Meta API failed: ${resp.status} ${await resp.text()}`);
  process.exit(1);
}
const { tables } = await resp.json();

const used = new Set(Object.values(KEY_OVERRIDES));
const keyed = tables.map((t) => ({
  key: KEY_OVERRIDES[t.id] ?? deriveKey(t.name, used),
  table: t,
}));
for (const k of keyed) used.add(k.key);

const today = new Date().toISOString().slice(0, 10);
const lines = [];
lines.push(`// AUTO-GENERATED by scripts/regenerate-schema.mjs on ${today}. DO NOT EDIT BY HAND.`);
lines.push(`// Field names are the EXACT Airtable display names (including emoji and special chars).`);
lines.push(`// Reference fields via bracket notation: Tables.Stories.fields["Story Status"].id`);
lines.push(`// Source of truth: live Airtable Meta API for base ${BASE_ID}.`);
lines.push(`//`);
lines.push(`// Regenerate: node scripts/regenerate-schema.mjs`);
lines.push(`// CI guard:   npm run verify-schema  (validates these IDs against the live Meta API)`);
lines.push(``);
lines.push(`export const BASE_ID = ${JSON.stringify(BASE_ID)};`);
lines.push(``);
lines.push(`export const Tables = {`);

for (const { key, table } of keyed) {
  lines.push(`  ${key}: {`);
  lines.push(`    id: ${JSON.stringify(table.id)},`);
  lines.push(`    name: ${JSON.stringify(table.name)},`);
  lines.push(`    fields: {`);
  for (const f of table.fields) {
    let entry = `{ id: ${JSON.stringify(f.id)}, type: ${JSON.stringify(f.type)}`;
    if (CHOICE_TYPES.has(f.type) && f.options?.choices) {
      const choices = f.options.choices.map((c) => ({ name: c.name }));
      entry += `, options: { choices: ${JSON.stringify(choices)} }`;
    }
    entry += ` }`;
    lines.push(`      ${JSON.stringify(f.name)}: ${entry},`);
  }
  lines.push(`    },`);
  lines.push(`  },`);
}

lines.push(`} as const;`);
lines.push(``);
lines.push(`export type TableKey = keyof typeof Tables;`);
lines.push(``);
lines.push(`// Convenience alias`);
lines.push(`export const T = Tables;`);
lines.push(``);

const out = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  console.log(current === out ? "schema.ts is up to date." : "schema.ts DIFFERS from live base.");
  process.exit(current === out ? 0 : 1);
}

writeFileSync(OUT, out, "utf8");
console.log(
  `Wrote lib/schema.ts — ${keyed.length} tables, ${tables.reduce((n, t) => n + t.fields.length, 0)} fields.`,
);
